### PR TITLE
T5741: Update dhclient lease path to /run/dhclient

### PR DESCRIPTION
**Pull request by mhamzahkhan**
https://vyos.dev/T5741

### CODE REVIEW

**Comment by AdamLantos** [comment]
Thanks! I was having issues with wan load-balancing on Sagitta builds (empty routing tables for wan DHCP interfaces), and this PR fixed them. Is there a reason not to merge this?

**Comment by mhamzahkhan** [comment]
Need one of the Vyos devs to review and merge it I guess :)

**Comment by dmbaturin** [comment]
@mhamzahkhan Thanks! Sorry we've overlooked the PR, looks like this repo was omitted from our review request setup — we'll fix that.

**Comment by sever-sever** [comment]
@MergifyIo backport sagitta

**Pull request merged**
